/* eslint-disable @next/next/no-html-link-for-pages */
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import tick from "../public/tick.svg"
import vector from "../public/vector.svg"

export default function Home() {

    
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-40 pt-24 flex justify-between w-screen h-screen">
        <div className="block py-14 text-left">
          <h1 className="text-white inter text-[2.5rem] dd">Beta Plans -</h1>
          <p className="text-white text-[1.75rem] font-medium py-4">
            <ul className="df ">
              <li> <img src="./tick.svg" /> <span>Custom Domains</span></li>
              <li> <img src="/tick.svg" /> <span>Tags</span></li>
              <li> <img src="/tick.svg" /> <span>Add Your Socials!</span></li>
              <li> <img src="/tick.svg" /> <span>Mobile Design Coming soon!</span></li>
            </ul>
          </p>
        </div>

        <Image 
            src={vector}
            height={300}
            width={300}
        />

      </main>
    </div>
  );
}