import Avatar from "@mui/material/Avatar";
import SocialoButton from "./Content/SocialoButton";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next"

function AboutContent() {
    return (
<div className="bg-[#816AFE] w-screen h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

      <main className="px-40 pt-24">
        <div className="flsex fslex-col text-left">
          <h1 className="text-white inter text-[2.75rem] dd">About Socialo</h1>
          <p className="text-white text-[2rem] w-[50%] font-bold py-10">
            A Place where people can <br />
            Whip Up their Own Portfolios, <br />
            with their Social media <br /> Accounts
          </p>
        </div>
      </main>
    </div>
    );
}

export default AboutContent;